spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/takecare
spring.datasource.username=postgres
spring.datasource.password=super

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


app.jwt.secret=${JWT_SECRET:VGFrZUNhcmUtRGV2ZWxvcG1lbnQtU2VjcmV0LUtleS1Gb3ItSldULVRva2Vucy0yMDI2}
app.jwt.expiration-ms=86400000